blank_issues_enabled: false
contact_links:
  - name: generic-infrastructure discussions
    url: https://github.com/orgs/generic-infrastructure/discussions
    about: Please ask and answer questions here.